### ISSUE TITLE
conf_estimation being set to null

### ISSUE THREAD

**Issue by sean-workman** [ml-struct-bio/drgnai#15]
Hi there

I am trying to use DRGN-AI to generate an initial _ab initio_ reconstruction of my particles but for whatever reason my config file is being altered by the program when I try to run it. My input `configs.yaml` is below:

```
particles: ~/sean/test1/inputs/particles.128.txt
ctf: ~/sean/test1/inputs/ctf.pkl
pose: null
quick_config:
  capture_setup: spa
  reconstruction_type: homo
  pose_estimation: abinit
  conf_estimation: autodecoder
lazy: true
batch_size_hps: 8
batch_size_sgd: 128
```

But when I look at it again after running `drgnai train .` from the same directory as `configs.yaml`, it has been altered to this:

```
particles: ~/sean/test1/inputs/particles.128.txt
ctf: ~/sean/test1/inputs/ctf.pkl
pose: null
quick_config:
  capture_setup: spa
  reconstruction_type: homo
  pose_estimation: abinit
  conf_estimation: null
lazy: true
batch_size_hps: 8
batch_size_sgd: 128
```

Is this expected behavior?
